# ----------------------- #
#      Main Configs       #
# ----------------------- #

theme: jekyll-theme-minimal
title: Блог инженера
email: mihail.kiselev@gmail.com
author: Mikhail Kiselev
description: Блог о минимализме, инжинерии и программировании.
twitter_username: sefard
subscribe_rss: /atom.xml
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed
paginate: 10          # Posts per page on the blog index

