# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Блог инженера
email: mihail.kiselev@gmail.com
author: Mikhail Kiselev
description: Блог о минимализме, инжинерии и программировании.
twitter: sefard
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mnlist.ru" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-144558799-1
comments: true
disqus: watery-jekyll

author: Mikhail Kiselev
author_bio: >-
  Приветствую в моём блоге! 😄 Меня зовут Михаил. Я инженер и программист. 
  Живу в Сибири, работаю на Сахалине, путешествую где придётся. 
  Я предпочитаю пост в блог посту в твиттер. Описание полезной технологии 
  или гаджета предпочитаю описанию заката или посиделок в кафе. 
author_pic: https://res.cloudinary.com/dlqc5rp9l/image/upload/v1624447606/blog/avatar/KMV_nw55ya.jpg

paginate: 12
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
permalink: /blog/:year/:title

subscribe_rss: /feed.xml

theme_switcher: false

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
