# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://kiselevmv.github.io
title: Блог инженера
author: Mikhail Kiselev
simple_search: https://google.com/search
description:
theme: jekyll-theme-minimal
subscribe_rss: /atom.xml
plugins: plugins
markdown: kramdown
paginate: 10          # Posts per page on the blog index
encoding: UTF-8       # Avoid "incompatible character encodings"

