# ----------------------- #
#      Main Configs       #
# ----------------------- #

theme: jekyll-theme-minimal
title: Блог инженера
email: mihail.kiselev@gmail.com
author: Mikhail Kiselev
description: Блог инженера, но не только об инжинерии. Я работаю инженером охраны труда, окружающей среды и промышленной безопасности. А увлекаюсь программированием.
twitter_username: sefard
subscribe_rss: /atom.xml
plugins:
  - jekyll-feed
markdown: kramdown
paginate: 10          # Posts per page on the blog index

