# ----------------------- #
#      Main Configs       #
# ----------------------- #

theme: jekyll-theme-minimal
title: Блог инженера
email: mihail.kiselev@gmail.com
author: Mikhail Kiselev
description: Блог о минимализме, инжинерии и программировании.
twitter: sefard
email: mihail.kiselev@gmail.com
subscribe_rss: /atom.xml
permalink: /blog/:year/:title
paginate: 15
kramdown:
  math_engine: mathjax
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
paginate: 10          # Posts per page on the blog index

